remote_theme: raviriley/agency-jekyll-theme

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/test" # the subpath of your site, e.g. /blog

title      : CV Enterprises
email      : contact@cventerprises.org #this is also the email contact forms will go to
description: "Real Students Solving Real-World Problems for Real Customers"
author     : Ravi Riley
logo:     #optional, defaults to site title
  path: assets\img\cv-ent-logo.png
  height: 40 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme