remote_theme: raviriley/agency-jekyll-theme

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/new" # the subpath of your site, e.g. /blog

title      : CV Enterprises
email      : contact@cventerprises.org #contact forms will go here
description: "Real Students Solving Real-World Problems for Real Customers"
author     : Ravi Riley
logo:     #optional, defaults to site title
  path: assets\img\cv-ent-logo.png
  height: 40 #height in px, defaults to 52px

locale: "en-US"

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

plugins:
  - jekyll-remote-theme